### ISSUE TITLE
Missing await for generateEmailResponse()

### ISSUE THREAD

**Issue by j12y** [nylas-samples/node-email-responder-ai#1]
I ran into a small problem with the **generate-email-response-with-email-body** branch. At first I was just getting a `[object Object]` output in the email interface.

It seemed that was coming from here:
https://github.com/nylas-samples/node-email-responder-ai/blob/generate-email-response-with-email-body/backend/route.js#L17
```
  const message = await nylas.messages.find(messageId);

  const emailBody = await removeHtml(message.snippet)
  
  const response = generateEmailResponse(emailBody);
  const responses = {};
```

It looks like a missing `await` for the `generateEmailResponse(emailBody)` so was only getting an unfulfilled promise. It was correct in the well done workshop. 

I also noticed that this was using the `message.snippet` which already is plain text, so depending on the goal might make more sense to remove HTML only from the `message.body`.

Hope that is helpful.

**Comment by relaxedtomato** [comment]
Hi @j12y, thanks for catching this, I recall finding this during the workshop, just didn't revisit it here. 

Let me make the [update](https://github.com/nylas-samples/node-email-responder-ai/pull/2) 👍 

Thanks for attending the workshop, which event did you attend?

For the purpose of completing the workshop, I decided to use `message.snippet`, however, have made some changes to account for using `message.body` just need to test out the [removeHtml](https://github.com/nylas-samples/node-email-responder-ai/blob/main/backend/utils/email-cleanup.js). 

Also using a shorter message is helpful with character API character limits (I think OpenAI was max 4000 chars the last time I checked).
